receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 5s
    send_batch_size: 512
  resource:
    attributes:
      - action: insert
        key: deployment.environment
        value: local

exporters:
  otlp/tempo:
    endpoint: tempo:4317    # Tempo gRPC endpoint
    tls:
      insecure: true

  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [otlp/tempo, debug]