spring:
  application:
    name: inventory-service

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0    # Sample 100% of requests
    enabled: true
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
logging:
  config: classpath:logback-spring.xml